import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import AppLayout from "./layout/AppLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={instrumentSans.className}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
